/* 
* Generated by
* 
*      _____ _          __  __      _     _
*     / ____| |        / _|/ _|    | |   | |
*    | (___ | | ____ _| |_| |_ ___ | | __| | ___ _ __
*     \___ \| |/ / _` |  _|  _/ _ \| |/ _` |/ _ \ '__|
*     ____) |   < (_| | | | || (_) | | (_| |  __/ |
*    |_____/|_|\_\__,_|_| |_| \___/|_|\__,_|\___|_|
*
* The code generator that works in many programming languages
*
*			https://www.skaffolder.com
*
*
* You can generate the code from the command-line
*       https://npmjs.com/package/skaffolder-cli
*
*       npm install -g skaffodler-cli
*
*   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *
*
* To remove this comment please upgrade your plan here: 
*      https://app.skaffolder.com/#!/upgrade
*
* Or get up to 70% discount sharing your unique link:
*       https://app.skaffolder.com/#!/register?friend=5dc9035ef1ef4518a538176b
*
* You will get 10% discount for each one of your friends
* 
*/
// START - USED SERVICES
/*
 *	userService.create
 *		PARAMS: 
 *		
 *
 *	userService.get
 *		PARAMS: 
 *					ObjectId id - Id resource
 *		
 *
 *	UserService.list
 *		PARAMS: 
 *		
 *
 *	userService.update
 *		PARAMS: 
 *					ObjectId id - Id
 *		
 *
 */
// END - USED SERVICES

// START - REQUIRED RESOURCES
/*
 * UserService  
 * userService  
 */
// END - REQUIRED RESOURCES

app.controller('userEditController', ['$scope', '$location', '$routeParams', '$q', 'UserService', 'userService', 'UserService',
    function ($scope, $location, $routeParams, $q, UserService , userService , UserService) {

    	//manage create and save
		$scope.external = {};
		
    	if ($routeParams.id != 'new')
    	{
        	$scope.id = $routeParams.id;
        	$scope.obj = userService.get({_id: $scope.id});
        	
    	}
    	else{
    		$scope.obj = new userService();
        	
    	}
    	
    	$scope.save = function(){
    		$scope.obj.$save().then(function(data){
    			$scope.obj=data;
        		$location.path('/users/');
    		});
    	}
    	
    	$scope.remove = function(){
    		userService.remove({_id: $scope.obj._id}).$promise.then(function(){
				$('#removeModal').modal('hide');
				$('.modal-backdrop').remove();
				$('.modal-open').removeClass("modal-open");
        		$location.path('/users/');
    		});
    	}
    	
    		
        //manage relation log
        		
    	$scope.list_User = UserService.query();

    	$scope.contain_User = function(item){
    		if (!$scope.obj.log) return false;
    		return $scope.obj.log.indexOf(item) != -1;
    	}
		    	
		$scope.add_User = function(item){
			if(!$scope.obj.log)
				$scope.obj.log = [];
			$scope.obj.log.push(item);
		}
		
		$scope.remove_User = function(index){
			$scope.obj.log.splice(index, 1);
		}
}]);