/* 
* Generated by
* 
*      _____ _          __  __      _     _
*     / ____| |        / _|/ _|    | |   | |
*    | (___ | | ____ _| |_| |_ ___ | | __| | ___ _ __
*     \___ \| |/ / _` |  _|  _/ _ \| |/ _` |/ _ \ '__|
*     ____) |   < (_| | | | || (_) | | (_| |  __/ |
*    |_____/|_|\_\__,_|_| |_| \___/|_|\__,_|\___|_|
*
* The code generator that works in many programming languages
*
*			https://www.skaffolder.com
*
*
* You can generate the code from the command-line
*       https://npmjs.com/package/skaffolder-cli
*
*       npm install -g skaffodler-cli
*
*   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *
*
* To remove this comment please upgrade your plan here: 
*      https://app.skaffolder.com/#!/upgrade
*
* Or get up to 70% discount sharing your unique link:
*       https://app.skaffolder.com/#!/register?friend=5dc9035ef1ef4518a538176b
*
* You will get 10% discount for each one of your friends
* 
*/
package com.login.db.login_db.entity.base;

/**
 * 
 * 
  _____                      _              _ _ _     _   _     _        __ _ _      
 |  __ \                    | |            | (_) |   | | | |   (_)      / _(_) |     
 | |  | | ___    _ __   ___ | |_    ___  __| |_| |_  | |_| |__  _ ___  | |_ _| | ___ 
 | |  | |/ _ \  | '_ \ / _ \| __|  / _ \/ _` | | __| | __| '_ \| / __| |  _| | |/ _ \
 | |__| | (_) | | | | | (_) | |_  |  __/ (_| | | |_  | |_| | | | \__ \ | | | | |  __/
 |_____/ \___/  |_| |_|\___/ \__|  \___|\__,_|_|\__|  \__|_| |_|_|___/ |_| |_|_|\___|
 
                                                                                   
 * DO NOT EDIT THIS FILE!! 
 *
 *  FOR CUSTOMIZE UserBase PLEASE EDIT ../User.java
 * 
 *  -- THIS FILE WILL BE OVERWRITTEN ON THE NEXT SKAFFOLDER CODE GENERATION --
 * 
 */
 

/**
 * This is the model of User object
 * 
 */
 
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Date;
import java.math.BigDecimal;


import org.springframework.jdbc.core.RowMapper;
import com.login.db.login_db.entity.User;

public class UserBase implements RowMapper<User>{
	
	private Long _id;
	
	// Attributes
    private Double 123;
	
	
	// Relations m:m log
	private ArrayList<Long> log;
	
	
	@Override
	public User mapRow(ResultSet rs, int rowNum) throws SQLException {
		
		User obj = new User();
		try {
			obj.set_id(rs.getLong("id"));
			obj.set123(rs.getDouble("123"));
			
        	
		}
		catch(Exception e) {
			e.printStackTrace();
		}
		return obj;
	}


	public Long get_id() {
		return _id;
	}

	public void set_id(Long _id) {
		this._id = _id;
	}
	
	public Double get123() {
		return 123;
	}


	public void set123(Double 123) {
		this.123 = 123;
	}
	
    
    
    
    
    // Relations m:m log
	public ArrayList<Long> getLog() {
		return log;
	}

	public void setLog(ArrayList<Long> log) {
		this.log = log;
	}
	
	
	public static class User_log implements RowMapper<User_log>{
		
		private Long _id;
		
		// Relations
	
		private Long id_user;
		private Long id_User;
				
		@Override
		public User_log mapRow(ResultSet rs, int rowNum) throws SQLException {
			
			User_log obj = new User_log();
			try {
				obj.set_id(rs.getLong("id"));
				obj.setId_user(rs.getLong("id_user"));
				obj.setId_User(rs.getLong("id_User"));
			}
			catch(Exception e) {
				e.printStackTrace();
			}
			return obj;
		}
		public Long get_id() {
			return _id;
		}
	
		public void set_id(Long _id) {
			this._id = _id;
		}
	
		public Long getId_user() {
			return id_user;
		}
	
	
		public void setId_user(Long id_user) {
			this.id_user = id_user;
		}
	
	
		public Long getId_User() {
			return id_User;
		}
	
	
		public void setId_User(Long id_User) {
			this.id_User = id_User;
		}
	}
    
}